### ISSUE TITLE
Wrong number generation

### ISSUE THREAD

**Issue by peter-perot** [joffreykern/vscode-markdown-toc#5]
Nice tool, but I found an issue which is currently preventing me from using it:

Take the following markdown:

``` markdown
# alpha
## bravo
### charlie
#### delta
### echo
#### foxtrott
### golf
```

The following TOC is generated:

``` markdown
<!-- vscode-markdown-toc -->
* 1. [bravo](#bravo-0)
	* 1.1. [charlie](#charlie-1)
		* 1.1.1. [delta](#delta-2)
	* 1.2. [echo](#echo-3)
		* 1.2.1. [foxtrott](#foxtrott-4)
	* 1.3.1. [golf](#golf-5)

<!-- /vscode-markdown-toc -->

# alpha
##  1. <a name='bravo-0'></a>bravo
###  1.1. <a name='charlie-1'></a>charlie
####  1.1.1. <a name='delta-2'></a>delta
###  1.2. <a name='echo-3'></a>echo
####  1.2.1. <a name='foxtrott-4'></a>foxtrott
###  1.3.1. <a name='golf-5'></a>golf
```

As you can see: `golf` is not correctly numbered.

It should be:

``` markdown
<!-- vscode-markdown-toc -->
* 1. [bravo](#bravo-0)
	* 1.1. [charlie](#charlie-1)
		* 1.1.1. [delta](#delta-2)
	* 1.2. [echo](#echo-3)
		* 1.2.1. [foxtrott](#foxtrott-4)
	* 1.3. [golf](#golf-5)

<!-- /vscode-markdown-toc -->

# alpha
##  1. <a name='bravo-0'></a>bravo
###  1.1. <a name='charlie-1'></a>charlie
####  1.1.1. <a name='delta-2'></a>delta
###  1.2. <a name='echo-3'></a>echo
####  1.2.1. <a name='foxtrott-4'></a>foxtrott
###  1.3. <a name='golf-5'></a>golf
```

The wrong number generation is continued on the next items so they run out of sync.

**Comment by peter-perot** [comment]
Why `headers.lenght - 2`? Maybe this is thd bug: https://github.com/joffreykern/vscode-markdown-toc/blob/master/src/extension.ts#L79

**Comment by joffreykern** [comment]
Hello @peter-perot,

Thanks for your feedback. 
I tried in my computer to fixed it with your purpose, and it's working good.

I'll update the extention this week !

**Comment by peter-perot** [comment]
Thank you, @joffreykern.

**Comment by peter-perot** [comment]
@joffreykern, currently I'm on vacation so I cannot create a test case, but I think we still could have a bug here.

I think, the line

``` csharp
let previousLevel: number = headers.length > 3 ? headers[headers.length - 1].level : this.maxLevel;
```

should read

``` csharp
let previousLevel: number = headers.length > 0 ? headers[headers.length - 1].level : 0;
```

This way on the first iteration with `headers.length === 0` the variable `previousLevel` is set to 0 (keep in mind that `this.maxLevel` is wrong anyway since the offset of 2 for the minimum level has not been subtracted).

Since `levels` is initialized with `[0, 0, 0]` nothing has to be reset on the first iteration.

Maybe this could be a test case:

```
### alpha

## bravo

### charlie
```

But, as said, I currently have no notebook available to check this.

**Comment by peter-perot** [comment]
Another proposal: I think we could drop the variable `previousLevel`. Simply reset all sublevels on each iteration:

``` javascript
// Have to reset the sublevels
for (var index = level; index < this.maxLevel - this.minLevel; index++) {
  levels[index + 1] = 0;
}
```

**Comment by peter-perot** [comment]
Let's simulate it:

```
  init: [0, 0, 0]
# alpha
  skipped
## bravo
  level 0, [0, 0, 0] -> reset on indices 1, 2, increment on index 0 -> [1, 0, 0]
  result: 1. bravo
### charlie
  level 1, [1, 0, 0] -> reset on index 2, increment on index 1 -> [1, 1, 0]
  result: 1.1. charlie
#### delta
  level 2, [1, 1, 0] -> nothing to reset, increment on index 2 -> [1, 1, 1]
  result: 1.1.1. delta
### echo
  level 1, [1, 1, 1] -> reset on index 2, increment on index 1 -> [1, 2, 0]
  result: 1.2. echo
#### foxtrott
  level 2, [1, 2, 0] -> nothing to reset, increment on index 2 -> [1, 2, 1]
  result: 1.2.1. foxtrott
### golf
  level 1, [1, 2, 1] -> reset on index 2, increment on index 1 -> [1, 3, 0]
  result: 1.3. golf
```

Perfect. ;-)

**Comment by peter-perot** [comment]
So, back at work. I just tested this code where I got rid of the `previousLevel` variable:

``` javascript
// Have to reset the sublevels
for (var index = level; index < this.maxLevel - this.minLevel; index++) {
  levels[index + 1] = 0;
}
```

Works perfectly.

In your current implementation you fill the array with `[0, 0, 0, 0, 0]` on the first iteration (since `this.maxLevel` is 4):

``` javascript
// Have to reset the sublevels
if(level < previousLevel){
  for (var index = level; index < previousLevel; index++) {
    levels[index + 1] = 0;
  }
}
```

This is kind of an "internal bug", since the array is larger than required. This is no "externally" visible bug, but the code is more consistent.
